version: '3.9'

services:
    lulu-database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - 8001:8010
        env_file:
            - ../.env
        networks:
            - lulu
        depends_on:
            - lulu-db
            
    lulu-db:
        build:
            context: ../db
            dockerfile: Dockerfile
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - lulu

networks:
    lulu:
        external: True
